import { initializeApp } from "https://www.gstatic.com/firebasejs/9.3.0/firebase-app.js";
import { getFirestore, doc, setDoc } from "https://www.gstatic.com/firebasejs/9.3.0/firebase-firestore.js";
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const products = [{
    id: 1,
    name: "PlayStation 5",
    price: 499.99,
    rating: 5.0,
    image: "./images/play5.jpg",
    images: [
        "./images/PlayStation5/one.png",
        "./images/PlayStation5/two.png",
        "./images/PlayStation5/three.png",
        "./images/PlayStation5/four.png",
        "./images/PlayStation5/five.png",
        "./images/PlayStation5/six.png",
        "./images/PlayStation5/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: true,
    type: "Consoles",
    discount: "",
    stock: "Stock",
    description: "Time to play at the next level",
    highlights: [
        "Marvel at incredible graphics and experience new PS5 features",
        "Maximize your play sessions with near-instant load times for installed PS5 games",
        "PS5 consoles support an 8K output, so you can play games on your 4320p resolution display",
        "Play your favorite PS5 games on your stunning 4K TV",
        "Enjoy smooth and fluid high frame rate gameplay at up to 120 fps for compatible games",
        "Immerse yourself in soundscapes where it feels as if the sound comes from every direction"
    ],
    relevance: 1,
    addShopCart: false
},
{
    id: 2,
    name: "SRS-XB23",
    rating: 4.8,
    price: 99.99,
    image: "./images/SRS-XB23.png",
    images: [
        "./images/SRS-XB23/one.png",
        "./images/SRS-XB23/two.png",
        "./images/SRS-XB23/three.png",
        "./images/SRS-XB23/four.png",
        "./images/SRS-XB23/five.png",
        "./images/SRS-XB23/six.png",
        "./images/SRS-XB23/seven.png",
    ],
    isColor: true,
    colors: ["Black", "Rose", "Blue", "Green", "white"],
    is10discount: false,
    is20discount: true,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Audio",
    discount: "20Discount",
    stock: "Stock",
    description: "EXTRA BASS™ Portable Bluetooth® Wireless Speaker",
    highlights: [
        "Play it loud with EXTRA BASS™ sound",
        "Waterproof, rustproof, dustproof and shockproof IP67 design for worry-free usage",
        "Power through any playlist with up to 12 hours of battery life",
        "Compact, lightweight, highly portable design",
        "Get things booming with Party Connect6 and sync up to 100 speakers",
        "X-Balanced Speaker Unit enhances sound quality and power"
    ],
    relevance: 2,
    addShopCart: false
},
{
    id: 3,
    name: "Xperia 5 II",
    price: 849.99,
    rating: 4.5,
    image: "./images/Xperia5II.png",
    images: [
        "./images/Xperia5II/one.png",
        "./images/Xperia5II/two.png",
        "./images/Xperia5II/three.png",
        "./images/Xperia5II/four.png",
        "./images/Xperia5II/five.png",
        "./images/Xperia5II/six.png",
        "./images/Xperia5II/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Phones",
    discount: "",
    stock: "Stock",
    description: "120Hz HDR OLED triple camera array smartphone with ZEISS® optics",
    highlights: [
        "21:9 120Hz4 6.1” HDR OLED display “powered by CineAlta”",
        "World’s first smartphone w/ 4K/120p for incredible slow motion video",
        "Alpha technology with Photography Pro for advanced controls and RAW",
        "Qualcomm® Snapdragon™ 865 Mobile Platform",
        "Keep on gaming; 4000mAh battery and graphene heat dissipation structure",
        "Large sensor and fast processor capture incredible low-light images"
    ],
    relevance: 3,
    addShopCart: false
},
{
    id: 4,
    name: "ZV-1",
    price: 699.99,
    rating: 4.3,
    image: "./images/ZV-1.png",
    images: [
        "./images/ZV-1/one.png",
        "./images/ZV-1/two.png",
        "./images/ZV-1/three.png",
        "./images/ZV-1/four.png",
        "./images/ZV-1/five.png",
        "./images/ZV-1/six.png",
        "./images/ZV-1/seven.png",
    ],
    isColor: true,
    colors: ["Black", "White"],
    is10discount: true,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Photography",
    discount: "10Discount",
    stock: "Stock",
    description: "Sony ZV-1 Camera for Content Creators and Vloggers",
    highlights: [
        "Large aperture 24-70mm F1.8-2.8 ZEISS® Vario-Sonnar T* lens",
        "Fast Hybrid AF, Real Time Eye-AF and Real-time AF tracking",
        "Quickly switch between two modes of defocused background bokeh",
        "High bitrate 4K movie w/ full pixel readout and no pixel binning",
        "Up to 24fps fast continuous shooting with AF/AE tracking",
        "Easy-to-push REC button with front facing Rec. tally light"
    ],
    relevance: 4,
    addShopCart: false
},
{
    id: 5,
    name: "XR-85Z9J",
    price: 8999.99,
    rating: 5.0,
    image: "./images/XR-85Z9J.png",
    images: [
        "./images/XR-85Z9J/one.png",
        "./images/XR-85Z9J/two.png",
        "./images/XR-85Z9J/three.png",
        "./images/XR-85Z9J/four.png",
        "./images/XR-85Z9J/five.png",
        "./images/XR-85Z9J/six.png",
        "./images/XR-85Z9J/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "House Technology",
    discount: "",
    stock: "Stock",
    description: "BRAVIA XR Z9J 8K HDR Full Array LED with Smart Google TV (2021)",
    highlights: [
        "Rediscover everything you watch with billions of accurate colors and see impressive picture quality that is natural and beautiful to the human eye.",
        "Precisely controlled backlighting brings out real-life depth and detail with deep blacks and high peak brightness.",
        "Revolutionary TV processing technology that understands how humans see and hear pushing 8K picture quality to the max with precise details, intense contrast, and natural colors",
    ],
    relevance: 5,
    addShopCart: false
},
{
    id: 6,
    name: "MDR-ZX310AP",
    price: 39.99,
    rating: 4.6,
    image: "./images/MDR-ZX310AP.png",
    images: [
        "./images/MDR-ZX310AP/one.png",
        "./images/MDR-ZX310AP/two.png",
        "./images/MDR-ZX310AP/three.png",
        "./images/MDR-ZX310AP/four.png",
        "./images/MDR-ZX310AP/five.png",
        "./images/MDR-ZX310AP/six.png",
        "./images/MDR-ZX310AP/seven.png",
    ],
    isColor: true,
    colors: ["Black", "Red", "Blue", "white"],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Audio",
    discount: "",
    stock: "Stock",
    description: "Wired On-ear Folding Headphones with Microphone",
    highlights: [
        "Lightweight, folding design for ultimate music mobility",
        "1.18 in neodymium drivers for powerful, balanced sound",
        "10-24,000 Hz frequency range",
        "Y-type cord, 3.94 ft length",
        "Choice of colors to suit your style"
    ],
    relevance: 6,
    addShopCart: false
},
{
    id: 7,
    name: "Far Cry 6",
    price: 99.99,
    rating: 4.0,
    image: "./images/farCry6.png",
    images: [
        "./images/FarCry6/one.png",
        "./images/FarCry6/two.png",
        "./images/FarCry6/three.png",
        "./images/FarCry6/four.png",
        "./images/FarCry6/five.png",
        "./images/FarCry6/six.png",
        "./images/FarCry6/seven.png",
    ],
    highlights: [
        "Play as Dani Rojas, a local Yaran and become a guerrilla fighter to liberate the nation",
        "Fight against Anton's troops in the largest Far Cry playground to date across jungles, beaches and Esperanza the capital city of Yara",
        "Employ makeshift weapons, vehicles, and Amigos, the new Fangs for Hire to burn the tyrannical regime to the ground",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Consoles",
    discount: "",
    stock: "Stock",
    description: "Fight alongside a modern-day guerrilla revolution to liberate Yara!",
    relevance: 7,
    addShopCart: false
},
{
    id: 8,
    name: "ICD-PX470",
    price: 79.99,
    rating: 4.5,
    image: "./images/ICD-PX470.png",
    images: [
        "./images/ICD-PX470/one.png",
        "./images/ICD-PX470/two.png",
        "./images/ICD-PX470/three.png",
        "./images/ICD-PX470/four.png",
        "./images/ICD-PX470/five.png",
        "./images/ICD-PX470/six.png",
        "./images/ICD-PX470/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: false,
    isLarge: false,
    type: "Audio",
    discount: "",
    stock: "noStock",
    description: "Stereo Digital Voice Recorder with Built-in USB",
    highlights: [
        "4 GB internal memory, expandable to 32 GB with micro SD",
        "S-microphone system records distant or quiet sounds clearly",
        "Focus and Wide-Stereo recording captures the voices you want to hear",
        "Auto voice recording reduces background noise",
        "Built-in USB connector makes transferring files easy"
    ],
    relevance: 8,
    addShopCart: false
},
{
    id: 9,
    name: "NW-A55",
    price: 219.99,
    rating: 4.3,
    image: "./images/NW-A55.png",
    images: [
        "./images/NW-A55/one.png",
        "./images/NW-A55/two.png",
        "./images/NW-A55/three.png",
        "./images/NW-A55/four.png",
        "./images/NW-A55/five.png",
        "./images/NW-A55/six.png",
        "./images/NW-A55/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Audio",
    discount: "",
    stock: "Stock",
    description: "Take music to the next level with incredible High-Resolution Audio fidelity",
    highlights: [
        "Precision engineered for improved sound quality",
        "Truly authentic sound with Hi-Res Audio",
        "S-Master HX™ digitAuto voice recording reduces background noiseal amplifier for pure sound quality",
        "Easy Bluetooth® connectivity with NFC™ One-touch",
        "Enjoy up to 45 hours of music playback"
    ],
    relevance: 9,
    addShopCart: false
},
{
    id: 10,
    name: "Xperia 1 III",
    price: 1000.99,
    rating: 4.6,
    image: "./images/SonyXperia1III.jpg",
    images: [
        "./images/Xperia1III/one.png",
        "./images/Xperia1III/two.png",
        "./images/Xperia1III/three.png",
        "./images/Xperia1III/four.png",
        "./images/Xperia1III/five.png",
        "./images/Xperia1III/six.png",
        "./images/Xperia1III/seven.png",
    ],
    isColor: true,
    colors: ["Black", "Violet"],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: true,
    type: "Phones",
    stock: "Stock",
    description: "Update you to the Sony Xperience 1 III",
    highlights: [
        "World’s first2 smartphone with 120Hz 6.5” 4K HDR OLED display",
        "Evolved Full-stage front facing stereo speakers – 40% louder",
        "Dedicated ergonomic shutter button with embossed finish",
        "Focus fast with Dual Photo Diode AF and 3D iToF sensors",
        "Cinematography Pro “powered by CineAlta” for advanced video rec",
        "5G connectivity and speed10; Qualcomm® Snapdragon™ 888 5G Mobile Platform"
    ],
    relevance: 10,
    addShopCart: false
},
{
    id: 11,
    name: "Spider-Man: Miles Morales",
    price: 49.99,
    rating: 4.8,
    image: "./images/spiderMan.png",
    images: [
        "./images/Spider-Man/one.png",
        "./images/Spider-Man/two.png",
        "./images/Spider-Man/three.png",
        "./images/Spider-Man/four.png",
        "./images/Spider-Man/five.png",
        "./images/Spider-Man/six.png",
        "./images/Spider-Man/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Consoles",
    discount: "",
    stock: "Stock",
    description: "With great power, there must also come great responsibility",
    highlights: [
        "The rise of Miles Morales - Miles Morales discovers explosive powers that set him apart from his mentor, Peter Parker. Master his unique, bioelectric venom blast attacks and covert camouflage power alongside spectacular web-slinging acrobatics, gadgets, and skills",
        "War for power - A war for control of Marvel's New York has broken out between a devious energy corporation and a high-technology criminal army. With his new home at the heart of the battle, Miles must learn the cost of becoming a hero and decide what he must sacrifice for the greater good"
    ],
    relevance: 11,
    addShopCart: false
},
{
    id: 12,
    name: "ILME-FX6V",
    price: 5999.99,
    rating: 4.8,
    image: "./images/ILME-FX6V.png",
    images: [
        "./images/ILME-FX6V/one.png",
        "./images/ILME-FX6V/two.png",
        "./images/ILME-FX6V/three.png",
        "./images/ILME-FX6V/four.png",
        "./images/ILME-FX6V/five.png",
        "./images/ILME-FX6V/six.png",
        "./images/ILME-FX6V/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Photography",
    discount: "",
    stock: "Stock",
    description: "Includes a full-frame image sensor to expand your cinematic creativity",
    highlights: [
        "4K full-frame sensor w/ 15+ stop dynamic range and high sensitivity",
        "Fast Hybrid AF w/ 627 phase-detection AF points and Eye-AF tracking",
        "Up to 4:2:2 10-bit QFHD 4K 120p, DCI 4K up to 60p and FHD 240p",
        "Electronically controlled optical variable ND filter (1/4 to 1/128)",
        "Selectable 12G/6G/3G SDI for up to 16-bit RAW 4K 60p output"
    ],
    relevance: 12,
    addShopCart: false
},
{
    id: 13,
    name: "BDP-S6700",
    rating: 4.3,
    price: 99.99,
    image: "./images/BDP-S6700.png",
    images: [
        "./images/BDP-S6700/one.png",
        "./images/BDP-S6700/two.png",
        "./images/BDP-S6700/three.png",
        "./images/BDP-S6700/four.png",
        "./images/BDP-S6700/five.png",
        "./images/BDP-S6700/six.png",
        "./images/BDP-S6700/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: true,
    isStock: true,
    isLarge: false,
    type: "House Technology",
    discount: "50Discount",
    stock: "Stock",
    description: "Blu-ray™ Player with 4K Upscaling and Wi/Fi for Streaming Video",
    highlights: [
        "Stunning picture with 4K upscaling (24p)",
        "Enjoy fast, stable streaming from a variety of internet video services",
        "Listen to music and watch videos via Bluetooth® with LDAC quality",
        "Stream music wirelessly around your home with Sony | Music Center Link",
        "Built-in Super Wi-Fi for a strong wireless signal"
    ],
    relevance: 13,
    addShopCart: false
},
{
    id: 14,
    name: "Final Fantasy VII remake",
    price: 59.99,
    rating: 5.0,
    image: "./images/FFVIIRemake.png",
    images: [
        "./images/FFVII/one.png",
        "./images/FFVII/two.png",
        "./images/FFVII/three.png",
        "./images/FFVII/four.png",
        "./images/FFVII/five.png",
        "./images/FFVII/six.png",
        "./images/FFVII/seven.png",
    ],
    isColor: false,
    colors: [],
    is10discount: false,
    is20discount: false,
    is50discount: false,
    isStock: true,
    isLarge: false,
    type: "Consoles",
    discount: "",
    stock: "Stock",
    description: "A new adaptation of the masterpiece of the Japanese role",
    highlights: [
        "A spectacular reimagining of one of the most visionary games",
        "The first game in the FINAL FANTASY VII REMAKE project, delivering a level of depth inconceivable for the original",
        "Mind-blowing story, unforgettable characters, epic battles and technical excellence collide",
        "Character Design: Tetsuya Nomura / Roberto Ferrari",
        "Cloud Strife, a former member of Shinra's elite SOLDIER unit now turned mercenary, lends his aid to the group, unaware of the epic consequences that await him."
    ],
    relevance: 14,
    addShopCart: false
},
];

products.forEach(async (product) => {
    await setDoc(doc(db, "products", `0124587FGH96IO${product.id}`), product);
});